import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Map Clerk's prebuilt components onto the app's semantic tokens (globals.css)
const clerkAppearance = {
  variables: {
    colorBackground: "var(--color-bg-panel)",
    colorForeground: "var(--color-text-primary)",
    colorMutedForeground: "var(--color-text-muted)",
    colorPrimary: "var(--color-accent-default)",
    colorPrimaryForeground: "var(--color-accent-on)",
    colorInput: "var(--color-input-bg)",
    colorInputForeground: "var(--color-input-text)",
    colorNeutral: "var(--color-text-primary)",
    colorBorder: "var(--color-border-strong)",
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="h-full">
        <ClerkProvider
          signInUrl="/sign-in"
          signUpUrl="/sign-up"
          appearance={clerkAppearance}
        >
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
